### ISSUE TITLE
There's nothing here?

### ISSUE THREAD

**Issue by tprk77** [mesonbuild/libzip#1]
When I tried to look at libzip on the Wrap DB, it says "Something went wrong No such project".

So I looked up this repo, and it seems there's nothing here?

The 1.6.1 branch is even with master. Maybe there was a bad push at some point?

**Comment by legeana** [comment]
No one submitted a wrap unfortunately.

**Comment by legeana** [comment]
https://github.com/mesonbuild/mesonwrap/issues/130 is fixed.
